GET http://localhost:3001/

### Lấy danh sách lì xì
GET http://localhost:3001/money
Content-Type: application/json

### Thêm một lì xì mới
POST http://localhost:3001/money
Content-Type: application/json

{
  "name": "hoang ha",
  "amount": 100000
}

### Xóa một lì xì (thay ID bằng ID thực tế)
DELETE http://localhost:3001/money/1706620800000
### Chúc Tết theo tên (truyền qua body)
POST http://localhost:3001/chuc
Content-Type: application/json

{
  "ten": "Nam"
}
